# name: Orchestrate terraform workflow

# on:
#   push:
#     branches:
#       - 'main'

# jobs:
#     apply-terraform-dos-dev:
#       name: Build read-write iam policies for dos dev account
#       uses: ./.github/workflows/action-infrastructure-stack.yaml
#       with:
#         ENV: dev
#       secrets: inherit
